### PR TITLE
Initial implementation of new API proposal

### PR DESCRIPTION
**Pull request by bjornharrtell**
This branch is an attempt to implement new API

### Initial new API proposal

```js
twkb.toGeoJSON(buffer, startOffset, howMany)
twkb.bboxToGeoJSON(buffer)
```

### Adjusted new API proposal

Rationale:  I see GeoJSON as a useful representation only with buffer reads, not streaming/partial reads. Another function (read) can return object representation suited for advanced stuff like streaming/partial reads or direct geometry conversion.

```js
twkb.toGeoJSON(buffer)
twkb.read(buffer, startOffset, howMany)
```

The output of read is an array of objects. Each object has a property type, ndims if other than the default 2 and bbox if exists. If howMany is used the object will also contain a property offset with the byte offset in the buffer when the limit is reached. Conditionally, if the type is a single geometry variant the object will have a property coordinates with the flat coordinates of the geometry. If the type is a multi geometry variant the object will have a property geoms that contains an array of flat coordinate arrays. Finally if the type is a collection the object will have a property geoms with an array of objects with the same structure as if parsed individually.

### TODO

* [x] Refactor code to separate modules
* [x] Implement toGeoJSON function
* [x] Implement read function
* [x] Support multi-types
* [x] Support collection
* [x] Support idlists
* [x] Support bbox
* [x] Support howMany (only for twkb.read)
* [x] Fix bugs in object representation
* [x] Document object representation
* [ ] Include ndims if other than 2 for all parsed objects
* [x] Fix bbox for ndims != 2
* [ ] Support bboxToGeoJSON (I don't understand the purpose of this one, not implementing for now)

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Test cases demonstrates usage. But here is a simple external code usage example:

```js
  // New API
  var twkb = require("twkb");
  var it = twkb.iterator(buffer);
  twkb.toGeoJSON(it);
```
```js
  // Old API
  var TWKB = require("twkb");
  var t = new TWKB(buffer);
  t.toGeoJSON();
```

So the API is very similar, it's just not not using classic OO. In the new API the module is a *library* of functions called twkb. In the old API the module is a *class* called TWKB. One benefit is that the new API makes it clear you get an iterator, where as the old API gives you an instance of the class TWKB which happens to work like a iterator.

The real benefit, I think, is that many functions are no longer dependant on mutable state (`this`) so they could easily be broken out to separate modules and unit tested separately. Also, perhaps @pramsey and @nicklasaven prefer a functional API, if that is a benefit I guess is in the eye of the beholder ;)

**Comment by bjornharrtell** [comment]
So the issue with collection is because I have messed up the state which was not as simple as I thought. 

The two states are used in the Feature class (the two constructor arguments) but I have a hard time understanding the original implementation. I guess it must have something to do with needing two cursors.

**Comment by javisantana** [comment]
it seems good for me.

About ``bboxToGeoJSON``. If you take a look at the ``read`` method it is useful to fetch only required geometries and that's the typical usecase when you have an spatial index and you want to decode only the features matched by a query.

There are two options to have such index, either calculating it somewhere or calculating it client side. ``bboxToGeoJSON`` decodes only the bounding boxes for the geometries so you can build the index without decoding all the geometries in memory.

It would work like:

```javascript
var bboxList = twkb.bboxToGeoJSON(buffer);
console.log(bboxList[0]);
```
this will print

```
{
"type": "Feature",
"properties": {
      startOffset: 10
},
"geometry": {
        "type": "Polygon",
        "coordinates": [ /*bbox coordinates */]
}
}
```

so you could do:

```
var features = [];
var spatialIndex = buildSpatialIndex(bboxList);
var featureIndex = spaitalIndex.intersects(geometry)
for(var i = 0; i < featureIndex.length; ++i) {
   features.push(twkb.read(buffer, featureIndex[i],startOffset, featureIndex[i],howMany));
}
```

Anyways, I think we can release without that method, nice work!

**Comment by bjornharrtell** [comment]
Thanks for the review!

**Pull request merged**
